### ISSUE TITLE
Port Forte to Psi4 1.1

### ISSUE THREAD

**Issue by fevangelista** [evangelistalab/forte#16]
With the release of Psi4 1.1 Forte no longer compiles.

**Comment by jeffschriber** [comment]
Seems we can remove all set_allow_desymmetrization(bool) calls, and the code will work properly. Not sure how to fix the "import forte" problem.

**Comment by fevangelista** [comment]
I removed the calls. The issue with import forte is connected to forte compiling with non-coda psi4. Try to add `-Dpsi4_DIR=/Users/fevange/Source/psi4/objdir/stage/usr/local/psi4/share/cmake/psi4 ` to the call to cmake.

**Comment by jeffschriber** [comment]
I'm getting another compiling issue with the following:

    /Users/jeffschriber/src/forte/src/mrdsrg-spin-free/dsrg_mrpt3.cc:4175:35: error: expected unqualified-id
                    ambit::Tensor B0 = ambit::Tensor::build(
    /usr/include/sys/termios.h:291:12: note: expanded from macro 'B0'
    #define B0      0
 
It seems like the compiler I'm using (Apple LLVM version 8.0.0 (clang-800.0.42.1)) is finding some previous definition of B0. This can easily be fixed by renaming the variable, but I'm surprised no one else got this error. What compiler were you using?
