### ISSUE TITLE
Compilation issue, cannot find boost header file

### ISSUE THREAD

**Issue by uwhbliu** [evangelistalab/forte#195]
Hi, I am compiling forte on a Ubuntu 18.04 machine. I have psi4 dev version installed and following the steps in README. I encounter the following error in the step of `make`
```
In file included from /PATH/forte/src/mrdsrg-helper/run_dsrg.h:10:0,
                         from /PATH/forte/src/api/forte_python_module.cc:57:
/PATH/src/mrdsrg-spin-integrated/dsrg_mrpt3.h:41:10: fatal error: boost/assign.hpp: No such file or directory
 #include "boost/assign.hpp"

compilation terminated.
```
I do have boost installed and the header file is in: /usr/local/include/boost/
How can I link to the boost header file during compilation? Thank you!

**Comment by lcyyork** [comment]
@uwhbliu Thank you for the interests in Forte and I am sorry for the late late reply. Can you tell me how you install Psi4 and Ambit? Due to changes of Pybind11, if you install Psi4 via conda, Forte needs to be compiled using Intel compilers. Otherwise, you need to compile your own Psi4 from source code.

The other useful piece of information is that your cmake configuration and the cmake output.

**Comment by lcyyork** [comment]
I am closing this issue for now and please reopen it if necessary.
