### ISSUE TITLE
Improve ACI/PCI initial guess

### ISSUE THREAD

**Issue by fevangelista** [evangelistalab/forte#24]
- [ ] Switch to CASCI guess with largest possible number of active orbitals given S, and Ms.

**Comment by jeffschriber** [comment]
This is mostly done. I wasn't totally sure how to select the active sub-space size for the guess, so that needs to be fixed. 

Additionally, the current code simply builds the reference determinants, and the diagonalization is left to whatever code calls it. I found this to be much easier when interfacing to ACI, but we could easily add diagonalization directly to the reference builder if needed.

**Comment by fevangelista** [comment]
Ok, I've got an algorithm written down. If you come to the HB I can give it to you right away.

**Comment by jeffschriber** [comment]
I think we can go ahead and close this, the CI_Reference class is now ready to use.
