### ISSUE TITLE
Reproducing DSRG-MRPT2 results  

### ISSUE THREAD

**Issue by huuco** [evangelistalab/forte#27]
Hi, 

I'm trying to reproduce the the results in the paper J. Chem. Phys. 146,124132 (2017) for N2.
In the supporting information
```
  R       CASSCF    u-DSRG-MRPT2    DSRG-MRPT2    r-DSRG-MRPT2   fr-DSRG-MRPT2
0.800 -108.48569238  -108.63027566  -108.63064658  -108.63094833  -108.63094825

```
Using the following input, I managed to have the correct CASSCF energy, but the DSRG-MRPT2 number does not match. What did I do wrong?
Thanks

  ==> DSRG-MRPT2 Energy Summary <==

```
    E0 (reference)                 =   -108.485692373441381
    <[F, T1]>                      =     -0.009292415956127
    <[F, T2]>                      =      0.007202136010542
    <[V, T1]>                      =      0.008439844902073
    <[V, T2]> (C_2)^4              =     -0.166025162246817
    <[V, T2]> C_4 (C_2)^2 HH       =      0.001133379752693
    <[V, T2]> C_4 (C_2)^2 PP       =      0.006271250454330
    <[V, T2]> C_4 (C_2)^2 PH       =      0.008950803079923
    <[V, T2]> C_6 C_2              =     -0.001319923417720
    <[V, T2]>                      =     -0.150989652377590
    DSRG-MRPT2 correlation energy  =     -0.144640087421103
    DSRG-MRPT2 total energy        =   -108.630332460862491
    max(T1)                        =      0.609191865576933
    max(T2)                        =      0.091887841339497
    ||T1||                         =      0.939612899751587
    ||T2||                         =      1.791629750051084
```

```
#!N2

import forte
memory 1 Gb

molecule N2 {
N          0.000000       0.000000       0.000000
N          0.000000       0.000000       0.800000
symmetry d2h
0 1
units ang
}

basis mybas{
  assign N cc-PVDZ 
}

set globals{
  basis mybas
  reference rhf
  scf_type CD
  df_ints_io     save
  cholesky_tolerance 1.0e-6
#                        Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u 
  docc             [     3,    0,    0,    0,    0,    2,    1,    1 ]
  restricted_docc  [     2,    0,    0,    0,    0,    2,    0,    0 ]
  active           [     1,    0,    1,    1,    0,    1,    1,    1 ]
  mcscf_maxiter 100
  nat_orbs true
}

scf_e, scf_wfn = energy('scf',                     return_wfn=True)
molden(scf_wfn, 'hf.molden')

cas_e, cas_wfn = energy('casscf', ref_wfn=scf_wfn, return_wfn=True)
molden(cas_wfn, 'casscf.molden', density_a=cas_wfn.get_opdm(0, 0, "A", True)) 

set forte {
    job_type              dsrg-mrpt2
    int_type              cholesky
    cholesky_tolerance    1e-6
    CAS_TYPE              fci
    root_sym              0
    nroot                 1
    dsrgpt                true
    dsrg_s                0.5
#                          Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u 
    frozen_docc      [     1,    0,    0,    0,    0,    1,    0,    0 ]
    restricted_docc  [     1,    0,    0,    0,    0,    1,    0,    0 ]
    active           [     1,    0,    1,    1,    0,    1,    1,    1 ]
}

energy('forte', ref_wfn = cas_wfn)  
```

**Comment by fevangelista** [comment]
@huuco : The discrepancy that you see is a consequence of recent changes in the way psi4 handles the canonicalization of CASSCF orbitals. It is caused by the fact that this computation has frozen orbitals. The DSRG-MRPT2 implementation is invariant with respect to unitary rotations of `restricted_docc`, `active`, and `restricted_uocc` orbitals. But in a computation like yours, where the CASSCF `restricted_docc` space includes two orbitals that are frozen in the DRSG-MRPT2, the energy will depend (slightly) on the way the CASSCF `restricted_docc` orbitals are canonicalized.

Currently, to get a reproducible answer just run the same input but remove the line:
```
   nat_orbs true
```
If you do not include this line psi4 will automatically generate *semicanonical orbitals* (they diagonalize the average CASSCF Fock matrix in the CASSCF `restricted_docc`, `active`, and `restricted_uocc` spaces). These orbitals are well defined and will provide a way to obtain reproducible results in Forte. Currently, there is still a minor issue with natural orbitals in psi4 (the `restricted_docc` and `restricted_uocc` blocks are not canonicalized), but once it will be fixed (probably very soon) calculations with semicanonical or natural orbitals will give the same answer.

Using conventional integrals you should get the following unrelaxed DSRG-MRPT2 energies:
```
semicanonical orbitals // remove nat_orbs keyword or set to false
DSRG-MRPT2 total energy        =   -108.630316306134731 / <-- correct

natural orbitals // nat_orbs true
DSRG-MRPT2 total energy        =   -108.630332753193144
```

with *Cholesky* the answers change slightly:
```
semicanonical orbitals // remove nat_orbs keyword or set to false
DSRG-MRPT2 total energy        =   -108.630316033614378

natural orbitals // nat_orbs true
DSRG-MRPT2 total energy        =   -108.630332460862306
```

You should take the numbers with the semicanonical orbitals (-108.63031630613) as the correct answer. The difference that you see from the published number (-108.63027566) is only 0.000040 Eh, which will not make a difference in the results. At this point you will not be able to reproduce the published values with the current version of psi4 because prior versions (which we used to generated the data in the paper) did not canonicalize CASSCF orbitals.

**Comment by lcyyork** [comment]
@huuco Just in case you are interested in all the r- and fr-DSRG-MRPT2 energies, here is a input that can do it:
```
import forte
memory 1 Gb

molecule N2 {
0 1
N          0.000000       0.000000       0.000000
N          0.000000       0.000000       0.800000
}

set globals{
  basis cc-pvdz
  reference rhf
  docc             [     3,    0,    0,    0,    0,    2,    1,    1 ]
  restricted_docc  [     2,    0,    0,    0,    0,    2,    0,    0 ]
  active           [     1,    0,    1,    1,    0,    1,    1,    1 ]
  mcscf_maxiter 100
}

cas_e, cas_wfn = energy('casscf', return_wfn=True)

set forte {
  job_type              mrdsrg
  CAS_TYPE              fci
  root_sym              0
  nroot                 1
  dsrg_s                0.5
#                        Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u 
  frozen_docc      [     1,    0,    0,    0,    0,    1,    0,    0 ]
  restricted_docc  [     1,    0,    0,    0,    0,    1,    0,    0 ]
  active           [     1,    0,    1,    1,    0,    1,    1,    1 ]
  semi_canonical true
  relax_ref  iterate
}

energy('forte', ref_wfn = cas_wfn)

```
At the end of the output, you will see
```
                  Fixed Ref. (a.u.)               Relaxed Ref. (a.u.)      
           -------------------------------  -------------------------------
    Iter.      Total Energy        Delta        Total Energy        Delta  
    -----------------------------------------------------------------------
        0     -108.630316306134 -1.086e+02     -108.630687873195 -1.086e+02
        1     -108.630987552074 -6.712e-04     -108.630987552417 -2.997e-04
        2     -108.630987459981  9.209e-08     -108.630987459981  9.244e-08
    -----------------------------------------------------------------------
    MRDSRG Total Energy            =    -108.630987459980730
    MRDSRG Total Energy (relaxed)  =    -108.630987459980858

```
From the 0th iteration, you will find the u-DSRG-MRPT2 and (pr-)DSRG-MRPT2 energies.
The r-DSRG-MRPT2 energy is the "fixed energy" of the first iteration and the fr-DSRG-MRPT2 is the "relaxed energy" of the last iteration [which is also printed as MRDSRG Total Energy (relaxed)].

The "mrdsrg" code is more general (pt2, pt3, ldsrg2, ...) but less efficient. Currently only the u-DSRG-MRPT2 and (pr-)DSRG-MRPT2 can be computed using the "dsrg-mrpt2" code.

By the way, the keyword "dsrgpt" is used for testing the renormalized two-electron integrals in the "mr-dsrg-pt2" code (which does not use ambit) and "dsrgpt" is not supported in "dsrg-mrpt2" nor "mrdsrg".

Let me know if you have further questions.

**Comment by huuco** [comment]
@fevangelista @lcyyork Thank you very much for your answer.

**Comment by fevangelista** [comment]
No problem. Glad we could help you. All these comments are helping us improve documentation and think about potential pitfalls users might encounter.

**Comment by lcyyork** [comment]
@huuco One thing I forget to mention. It is probably better to use "three-dsrg-mrpt2" instead of "dsrg-mrpt2" if the integrals are set to "cholesky" or "df", because dsrg-mrpt2 will form the four-index integrals of size hole^2 * particle^2.
